### ISSUE TITLE
Help message for "BLAST highlighted region" is incomplete

### ISSUE THREAD

**Issue by ihh** [GMOD/jblast-jbconnect-hook#230]
The help message for "BLAST highlighted region" reads as follows:

> Highlight the region by clicking the start coordinate in the track area of the genome browser, holding down and dragging to the end coordinate and releasing. The BLAST button will then appear in the tool button area.

This procedure by itself is insufficient to highlight a region. The user first needs to click on the "highlight" button in the toolbar.

At the moment, the highlight button seems to be auto-magically clicked when the error message is displayed. This is confusing: trying to perform an action (in this case, BLASTing) without specifying parameters (in this case, the highlighted region) should either put the program in a clearly-identified modal state where the user is _forced_ to specify parameters, or (more straightforwardly) it should provide a complete recipe for how the user should do this; not half and half.

See also #229

**Comment by enuggetry** [comment]
The message "Highlight the region by clicking...", which shows upon selection the menu item "BLAST highlighted region", is not an error message but are actually instructions for proceeding.

Perhaps the message should be more clear by starting with:
"The highlight mode has been invoked.  ..."  or simply not invoke it automatically.

The menu item and popup message was suggested since a new user may not be familiar with the procedure for highlighting a region.

Perhaps I should also include an image of what the highlight button looks like as well as the blast button that would appear after highlighting.

Proposed new message might look like:
"This feature allows you to select an arbitrary region to BLAST using the highlight region feature of JBrowse.

To begin, click the highlight button [image] on the toolbar to begin the highlight mode.
Highlight the region by clicking the start coordinate in the track area of the genome browser, holding down and dragging to the end coordinate and releasing. The BLAST button [image] will then appear in the tool button area.  Click the BLAST button to blast the highlighted region."

**Comment by ihh** [comment]
I think the correct thing is to _not_ activate the highlight button automatically, but guide the user to do it themselves. So yes, something like the text you propose would be fine. I don't have a strong opinion on whether the error message should also include an image of the highlight button; I guess it would be a good thing if it's easy to implement.

**Comment by enuggetry** [comment]
Resolved as part of #229
